# fly.toml app configuration file generated for nuzlocke-tracker-app on 2023-07-15T09:55:21+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nuzlocke-tracker-app"
primary_region = "hkg"

[build]
  [build.args]
    NEXT_PUBLIC_SERVER_URL = "https://nuzlocke-tracker-app.fly.dev/api/graphql"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
